


path = /usr/share/arduino
BOARD_TAG    = uno  # for mega use mega2560
ARDUINO_PORT = /dev/ttyACM0  # change this to the port used by your board
# added libraries used in the scketch 
ARDUINO_LIBS = DHT_sensor_library
ARDUINO_LIBS+= Adafruit_Unified_Sensor
include $(path)/Arduino.mk

